new update way

diff --git a/stratum b/stratum
--- a/stratum
+++ b/stratum
@@ -62,7 +62,7 @@ while ! [[ -s $HOME/$conf_file && -s $HOME/$func_file && -d $HOME/.stratum && -d
 done
 }
 
-update () {
+update_stratum () {
   if [ -z "$update_file" ]
   then
     update_file=stratum
@@ -89,6 +89,37 @@ update () {
     cp /stratum/$update_file.new /stratum/$update_file 2>/dev/null
       echo -e '\e[32m chmod +x ...\e[0m'
       echo -e $"\e[32m file:\e[0m\e[33m $update_file\e[32m updated...\e[0m" | logline
+  fi
+}
+
+# update any file from stratum
+update () {
+  if [ -z "$update_file" ]
+  then
+    update_file=/stratum/stratum
+    echo -e '\e[31m CAUTION! update itself ...  \e[0m\e[0m'
+  else
+    update_file=$update_file
+  fi
+  echo -e "\e[44m start update file:\e[0m\e[33m $update_file\e[0m" | logline
+  if ! wget -nv -O $update_file.new --no-check-certificate $repo_url/node$update_file; then
+    echo -e "\e[41m\e[33m ERROR: there is no file \e[97m$repo_url$update_file\e[41m\e[33m on the server\e[97m \
+ \e[0mor no response!\e[0m check again ..." | logline
+    rm -rf $update_file.new
+    exit 1
+  else
+    rm -rf $backup_dir/$update_file.bak
+      echo -e "\e[32m backup copy ...\e[0m"
+    cp $update_file $backup_dir$update_file.bak
+      echo -e "\e[35m backup file: $backup_dir$update_file.bak ...just in case...\e[0m"
+      echo -e "\e[32m remove existing oryginal ...\e[0m"
+    ln -s $backup_dir$update_file.bak $update_file.bak 2>/dev/null # symlink link
+    rm -rf $update_file
+      echo -e '\e[32m copy new one...\e[0m'
+    chmod +x $update_file.new
+    cp $update_file.new $update_file 2>/dev/null
+      echo -e '\e[32m chmod +x ...\e[0m'
+      echo -e "\e[32m file:\e[0m\e[33m $update_file\e[32m updated...\e[0m" | logline
   fi
 }
 
