move finctions and config

diff --git a/stratum b/stratum
--- a/stratum
+++ b/stratum
@@ -1,4 +1,50 @@
 #!/usr/bin/env bash
+# StratumOS - remote controlled linux system
+SCRIPT=${0##*/}
+ARGS=${@}
+if [[ $ARGS == "" ]]; then echo "no args"; fi
+URL_01=http://stratumos.com # main repository server
+GIT_01=https://github.com/StratumOS/StratumOS # main git server
+CONF=.stratum.conf
+STRATUM_DIR=/stratum
+
+init () {
+  if [[ -s ./$CONF && -d $HOME/.stratum && -d /stratum ]]; then
+    source ./$CONF
+  else
+    mkdir $HOME/.stratum 2>/dev/null
+    mkdir /stratum 2>/dev/null
+    if ! wget -nv -O ./$CONF --no-check-certificate $URL_01/$CONF; then
+      echo -e "\e[101m\e[30m ERROR: there is no file \e[0m\e[34m"$CONF"\e[0m on the server or no response! exit ...\e[0m"
+      exit 1
+    else
+      echo -e "OK: download file "$CONF" from "$URL_01
+    fi
+    exit
+  fi
+}
+
+update () {
+  echo -e "\e[44m start update file: "$SCRIPT" ...\e[0m\e[31m CAUTION! update itself ...  \e[0m" | logline
+  if ! wget -nv -O /stratum/stratum.new --no-check-certificate $URL_01/$SCRIPT; then
+    echo -e "\e[101m\e[30m ERROR: there is no file "stratum" on the server or no response! check again ...\e[0m" | logline
+    exit 1
+  else
+    rm -rf $BACKUP/$SCRIPT.bak
+      echo -e '\e[32m backup copy ...\e[0m'
+    cp /stratum/stratum $BACKUP/stratum.bak
+      echo -e '\e[35m backup file: '$BACKUP'/'$SCRIPT.bak' ...just in case...\e[0m'
+      echo -e '\e[32m remove existing oryginal ...\e[0m'
+    rm -rf /stratum/stratum
+      echo -e '\e[32m copy new one...\e[0m'
+    cp /stratum/stratum.new /stratum/stratum 2>/dev/null
+      echo -e '\e[32m chmod +x ...\e[0m'
+    chmod +x /stratum/stratum
+    echo -e $"\e[32m file: \"stratum\" updated...\e[0m" | logline
+  fi
+  exit 0
+}
+
 logline() {
     while IFS= read -r line; do
       case $line in
@@ -14,16 +60,24 @@ logline() {
     done
 }
 
-SCRIPT=${0##*/}
-mkdir /stratum 2>/dev/null
-mkdir $HOME/.stratum 2>/dev/null
+
+root_check () {
+if [ "$USER" != "root" ];then
+		echo -e "\e[31mRun this script as root! exit...\e[0m"
+		echo "Run this script as root! exit..." | logline; exit
+	else
+		echo -e "\e[32mStart OK ...\e[0m" | logline
+fi
+}
+
 touch /var/log/stratum.log 2>/dev/null; chmod 666 /var/log/stratum.log 2>/dev/null | logline
 LOGFILE=/var/log/stratum.log
 BACKUP=/var/backups/stratum
-REPO_URL=http://stratumos.com
 mkdir $BACKUP 2>/dev/null
 
-echo -e "\e[42m\e[30mOK\e[0m\e[33m Vars: \e[32m REPO_URL=\e[0m"$REPO_URL "\e[32m LOGFILE=\e[0m"$LOGFILE
+echo -e "\e[42m\e[30mOK\e[0m\e[33m\e[32m SCRIPT=\e[0m\e[94m"$SCRIPT \
+"\e[0m\e[33m\e[32m ARGS=\e[0m\e[94m"$ARGS \
+"\e[0m\e[32m REPO_URL=\e[0m"$REPO_URL "\e[32m LOGFILE=\e[0m"$LOGFILE
 echo -e "\e[32m $(date +%F' '%T) $SCRIPT - Start script ...\e[0m" >> $LOGFILE
 
 export_path () {
@@ -46,138 +100,10 @@ check_distro () {
 lsb_release -d | logline
 uname -a | logline
 }
-
-install_stuff_1() {
-  echo -e "\e[42m \e[0m\e[92m install_stuff_1: screen ntpdate unzip lsb-release ...\e[0m" | logline
-  apt -y install screen | logline
-  /usr/bin/screen -dmS stratum-watchdog '' &
-  apt -y install ntpdate unzip lsb-release
-  ntpdate -s time.nist.gov | logline
-  date | logline
-}
-
-root_check () {
-if [ "$USER" != "root" ];then
-		echo -e "\e[31mRun this script as root! exit...\e[0m"
-		echo "Run this script as root! exit..." | logline; exit
-	else
-		echo -e "\e[32mStart OK ...\e[0m" | logline
-fi
-}
-
-create_busyuser () {
-busyuser=busyman
-groupadd $busyuser
-useradd $busyuser -s /bin/bash -m -g $busyuser
-# allow execute crontab for busyuser
-cat > /etc/cron.allow << EOF
-$busyuser
-EOF
-EOF 2>/dev/null # without this line code colors in Atom editor are crazy
-
-echo -e "\e[104m \e[0m\e[94m user busyman created ...\e[0m" | logline
-cat /etc/cron.allow
-}
-
-rm_files () {
-  if [ -z $./var/backups/dpkg*.gz ];then
-  	rm /var/backups/dpkg*.gz
-  fi
-  if [ -z $./var/cache/apt/*.bin ];then
-  	rm /var/cache/apt/*.bin
-  fi
-  if [ -z $./var/cache/debconf/* ];then
-  	rm /var/cache/debconf/*
-  fi
-  if [ -z $./var/cache/apt/archives/*.deb ];then
-  	rm /var/cache/apt/archives/*.deb
-  fi
-  if [ -z $./var/lib/apt/lists/*.* ];then
-  	rm /var/lib/apt/lists/*.*
-  fi
-  if [ -z $./etc/apt/apt.conf ];then
-  	rm /etc/apt/apt.conf
-  fi
-}
-
-apt_files () {
-echo -e "\e[35m create /etc/apt/apt.conf and add Debian Jessie main repo ... \e[0m"
-echo 'APT::Install-Recommends "false" ; APT::Install-Suggests "false" ;' >> /etc/apt/apt.conf
-rm /etc/apt/sources.list
-echo 'deb http://ftp.debian.org/debian jessie main' >> /etc/apt/sources.list
-apt-get update && apt-get clean
-}
-
-install_ssh () {
-  apt-get -qq install -f --no-install-recommends openssh-server | logline
-  echo -e "\e[93m #allow root ssh login,, sed -i 's/without-password/yes/g' /etc/ssh/sshd_config \e[0m" | logline
-  sleep 1
-  sed -i 's/without-password/yes/g' /etc/ssh/sshd_config
-  echo -e "\e[34m service sshd reload && service sshd status ... \e[0m" | logline
-  service sshd reload | logline
-  service sshd status | logline
-}
-
-clean_apt () {
-  echo -e "\e[35m apt-get --purge autoremove && apt-get clean..................\e[0m" | logline
-  apt-get -qq --purge autoremove && apt-get clean
-}
-
-download_source_from_github () {
-cd /tmp
-wget -nv -O /tmp/master.zip --no-check-certificate https://github.com/StratumOS/StratumOS/archive/master.zip
-unzip -o ./master.zip
-rm ./master.zip
-cd /tmp/StratumOS-master
-ls -la
-}
-
-show_info () {
-  echo -e "\e[42m \e[30m  |-->\e[0m\e[32m Show info ... "
-  ip addr
-  echo -e "\e[35m Done ... \e[0m"
-}
-
-help (){
-  echo
-  echo "# arguments called with ---->  ${@}     "
-  echo "# \$1 ---------------------->  $1       "
-  echo "# \$2 ---------------------->  $2       "
-  echo "# path to me --------------->  ${0}     "
-  echo "# parent path -------------->  ${0%/*}  "
-  echo "# my name ------------------>  ${0##*/} "
-  echo
-  echo -e "\e[107m\e[30m ALERTS: \e[0m \e[42m\e[30m OK \e[0m\e[32m -SUCESS, \e[44m\e[37m I \e[0m\e[94m -INFO, \
-  \e[100m\e[97m I \e[0m\e[97m -LIGHT_INFO, \e[100m\e[37m I \e[0m\e[90m -DARK_INFO, \
-  \e[45m\e[30m ? \e[0m\e[95m -QUESTION, \e[43m\e[30m ! \e[0m\e[33m -WARNING, \
-  \e[105m\e[30m ? \e[0m\e[95m -LIGHT_QUESTION, \e[103m\e[30m ! \e[0m\e[33m -LIGHT_WARNING, \
-  \e[101m\e[30m ! \e[0m\e[91m -DANGER, \e[41m\e[37m<\e[30m!!\e[37m>\e[0m\e[31m -CRITICAL, "
-  echo
-  echo -e '\e[32m syntax:\n\
-  stratum [place:action] [--arg1] [--arg1]\e[0m' | logline
-}
-
 case $1 in
   --update|stratum:update|stratum:u|str:u)
 		root_check
-		echo -e "\e[44m start update file: "stratum" ...\e[0m\e[31m CAUTION! update itself ...  \e[0m" | logline
-		if ! wget -nv -O /stratum/stratum.new --no-check-certificate $REPO_URL/stratum; then
-			echo -e "\e[101m\e[30m ERROR: there is no file "stratum" on the server or no response! check again ...\e[0m" | logline
-			exit 1
-		else
-			rm -rf $BACKUP/stratum.bak
-				echo -e '\e[32m backup copy ...\e[0m'
-			cp /stratum/stratum $BACKUP/stratum.bak
-				echo -e '\e[35m backup file: '$BACKUP/stratum.bak' ...just in case...\e[0m'
-				echo -e '\e[32m remove existing oryginal ...\e[0m'
-			rm -rf /stratum/stratum
-				echo -e '\e[32m copy new one...\e[0m'
-			cp /stratum/stratum.new /stratum/stratum 2>/dev/null
-				echo -e '\e[32m chmod +x ...\e[0m'
-			chmod +x /stratum/stratum
-			echo -e $"\e[32m file: \"stratum\" updated...\e[0m" | logline
-		fi
-		exit 0
+    update
 	;;
   --help|-h)
     help
@@ -185,7 +111,7 @@ case $1 in
   xterm:htop)
     echo -e '\e[32m OK, execute htop in xterm terminal ... \e[0m' | logline
   ;;
-  --full|--all|-0|--init|init)
+  --full|--all|-0)
     export_path
     check_distro
     root_check
