new functions

diff --git a/stratum b/stratum
--- a/stratum
+++ b/stratum
@@ -7,27 +7,33 @@ URL_01=http://stratumos.com # main repository server
 GIT_01=https://github.com/StratumOS/StratumOS # main git server
 CONF=.stratum.conf
 STRATUM_DIR=/stratum
+source ./$CONF
 
 init () {
-  if [[ -s ./$CONF && -d $HOME/.stratum && -d /stratum ]]; then
-    source ./$CONF
+rm /stratum/.stratum.conf; echo "remove config file and download again ..."
+while ! [[ -s ./$CONF && -d $HOME/.stratum && -d /stratum && -s /stratum/stratum ]]; do
+  mkdir $HOME/.stratum 2>/dev/null
+  mkdir /stratum 2>/dev/null
+  cp ./stratum /stratum/stratum 2>/dev/null # copy
+  rm ./stratum # remove from this path
+  ln -s /stratum/stratum $HOME$STRATUM_DIR 2>/dev/null # symlink link
+  ln -s /stratum/.stratum.conf $HOME/$CONF 2>/dev/null # symlink link
+  ln -s /stratum/stratum /usr/bin/stratum 2>/dev/null # symlink link
+  if ! wget -nv -O /stratum/$CONF --no-check-certificate $URL_01/$CONF; then
+    echo -e "\e[101m\e[30m ERROR: there is no file \e[0m\e[34m"$CONF"\e[0m on the server" $URL_01\
+    " or no response! exit ...\e[0m"
+    exit 1
   else
-    mkdir $HOME/.stratum 2>/dev/null
-    mkdir /stratum 2>/dev/null
-    if ! wget -nv -O ./$CONF --no-check-certificate $URL_01/$CONF; then
-      echo -e "\e[101m\e[30m ERROR: there is no file \e[0m\e[34m"$CONF"\e[0m on the server or no response! exit ...\e[0m"
-      exit 1
-    else
-      echo -e "OK: download file "$CONF" from "$URL_01
-    fi
-    exit
+    echo -e "\e[100m\e[97m I \e[0m\e[97m OK: download file "$CONF" from \e[0m"$URL_01
   fi
+done
 }
 
 update () {
   echo -e "\e[44m start update file: "$SCRIPT" ...\e[0m\e[31m CAUTION! update itself ...  \e[0m" | logline
   if ! wget -nv -O /stratum/stratum.new --no-check-certificate $URL_01/$SCRIPT; then
-    echo -e "\e[101m\e[30m ERROR: there is no file "stratum" on the server or no response! check again ...\e[0m" | logline
+    echo -e "\e[101m\e[30m ERROR: there is no file "stratum" on the server" $URL_01\
+    " or no response! check again ...\e[0m" | logline
     exit 1
   else
     rm -rf $BACKUP/$SCRIPT.bak
@@ -52,8 +58,7 @@ logline() {
           echo -e "\e[30m ! \e[0m\e[33m -LIGHT_WARNING"
           ;;
           *)
-            echo -e "\e[100m\e[97m I \e[0m\e[97m -LIGHT_INFO"
-            ;;
+          ;;
       esac
         echo -e "$(date +%F' '%T) $SCRIPT - $line"
         echo "$(date +%F' '%T) $SCRIPT - $line" >> $LOGFILE
@@ -65,7 +70,7 @@ if [ "$USER" != "root" ];then
 		echo -e "\e[31mRun this script as root! exit...\e[0m"
 		echo "Run this script as root! exit..." | logline; exit
 	else
-		echo -e "\e[32mStart OK ...\e[0m" | logline
+		echo -e "\e[32mStart OK ... as root\e[0m" | logline
 fi
 }
 
