move functions to .stratum.func

diff --git a/stratum b/stratum
--- a/stratum
+++ b/stratum
@@ -1,38 +1,49 @@
 #!/usr/bin/env bash
 # StratumOS - remote controlled linux system
+# install as root: stratum --init
+# use as user: stratum [--help|-h|-?]
+
 SCRIPT=${0##*/}
 ARGS=${@}
-if [[ $ARGS == "" ]]; then echo "no args"; fi
-URL_01=http://stratumos.com # main repository server
-GIT_01=https://github.com/StratumOS/StratumOS # main git server
-CONF=.stratum.conf
+REPO_URL=http://stratumos.com # main repository server
+GIT_URL=https://github.com/StratumOS/StratumOS # main git server
+CONF=.stratum.conf # config file
+FUNC=.stratum.func # bash functions file
 STRATUM_DIR=/stratum
 source ./$CONF
 
 init () {
 rm /stratum/.stratum.conf; echo "remove config file and download again ..."
-while ! [[ -s ./$CONF && -d $HOME/.stratum && -d /stratum && -s /stratum/stratum ]]; do
-  mkdir $HOME/.stratum 2>/dev/null
-  mkdir /stratum 2>/dev/null
-  cp ./stratum /stratum/stratum 2>/dev/null # copy
-  rm ./stratum # remove from this path
-  ln -s /stratum/stratum $HOME$STRATUM_DIR 2>/dev/null # symlink link
-  ln -s /stratum/.stratum.conf $HOME/$CONF 2>/dev/null # symlink link
-  ln -s /stratum/stratum /usr/bin/stratum 2>/dev/null # symlink link
-  if ! wget -nv -O /stratum/$CONF --no-check-certificate $URL_01/$CONF; then
-    echo -e "\e[101m\e[30m ERROR: there is no file \e[0m\e[34m"$CONF"\e[0m on the server" $URL_01\
+while ! [[ -s ./$CONF && -s ./$FUNC && -d $HOME/.stratum && -d /stratum && -s /stratum/stratum ]]; do
+  mkdir $HOME/.stratum 2>/dev/null # user's stratum directory
+  mkdir $STRATUM_DIR 2>/dev/null # main stratum directory
+  cp ./stratum $STRATUM_DIR/stratum 2>/dev/null # copy from current path to main dir
+  rm ./stratum # remove from current path
+  ln -s $STRATUM_DIR/stratum $HOME/stratum 2>/dev/null # symlink link
+  ln -s $STRATUM_DIR/.stratum.conf $HOME/$CONF 2>/dev/null # symlink link
+  ln -s $STRATUM_DIR/.stratum.func $HOME/$FUNC 2>/dev/null # symlink link
+  ln -s $STRATUM_DIR/stratum /usr/bin/stratum 2>/dev/null # symlink link
+  if ! wget -nv -O /stratum/$CONF --no-check-certificate $REPO_URL/$CONF; then
+    echo -e "\e[101m\e[30m ERROR: there is no file \e[0m\e[34m"$CONF"\e[0m on the server" $REPO_URL\
     " or no response! exit ...\e[0m"
     exit 1
   else
-    echo -e "\e[100m\e[97m I \e[0m\e[97m OK: download file "$CONF" from \e[0m"$URL_01
+    echo -e "\e[100m\e[97m I \e[0m\e[97m OK: download file "$CONF" from \e[0m"$REPO_URL
+  fi
+  if ! wget -nv -O /stratum/$FUNC --no-check-certificate $REPO_URL/$FUNC; then
+    echo -e "\e[101m\e[30m ERROR: there is no file \e[0m\e[34m"$FUNC"\e[0m on the server" $REPO_URL\
+    " or no response! exit ...\e[0m"
+    exit 1
+  else
+    echo -e "\e[100m\e[97m I \e[0m\e[97m OK: download file "$FUNC" from \e[0m"$REPO_URL
   fi
 done
 }
 
 update () {
   echo -e "\e[44m start update file: "$SCRIPT" ...\e[0m\e[31m CAUTION! update itself ...  \e[0m" | logline
-  if ! wget -nv -O /stratum/stratum.new --no-check-certificate $URL_01/$SCRIPT; then
-    echo -e "\e[101m\e[30m ERROR: there is no file "stratum" on the server" $URL_01\
+  if ! wget -nv -O /stratum/stratum.new --no-check-certificate $REPO_URL/$SCRIPT; then
+    echo -e "\e[101m\e[30m ERROR: there is no file "stratum" on the server" $REPO_URL\
     " or no response! check again ...\e[0m" | logline
     exit 1
   else
@@ -83,7 +94,7 @@ info_bar () {
 echo -e "\e[42m\e[30mOK\e[0m\e[33m\e[32m SCRIPT=\e[0m\e[94m"$SCRIPT \
 "\e[0m\e[33m\e[32m ARGS=\e[0m\e[94m"$ARGS \
 "\e[0m\e[33m\e[32m USER=\e[0m\e[93m"$USER \
-"\e[0m\e[32m URL_01=\e[0m"$URL_01 "\e[32m LOGFILE=\e[0m"$LOGFILE
+"\e[0m\e[32m REPO_URL=\e[0m"$REPO_URL "\e[32m LOGFILE=\e[0m"$LOGFILE
 echo -e "\e[32m $(date +%F' '%T) $SCRIPT - Start script ...\e[0m" >> $LOGFILE
 }
 info_bar
@@ -109,6 +120,9 @@ lsb_release -d | logline
 uname -a | logline
 }
 case $1 in
+  --init|-i)
+    init
+    ;;
   --update|stratum:update|stratum:u|str:u)
 		root_check
     update
